/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as TruyCapAppRouteImport } from './routes/truy-cap-app'
import { Route as SanPhamRouteImport } from './routes/san-pham'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as KienThucRouteImport } from './routes/kien-thuc'
import { Route as KhoiNghiepRouteImport } from './routes/khoi-nghiep'
import { Route as KenhAffiliateRouteImport } from './routes/kenh-affiliate'
import { Route as HocVienRouteImport } from './routes/hoc-vien'
import { Route as HocAiRouteImport } from './routes/hoc-ai'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CongCuAiRouteImport } from './routes/cong-cu-ai'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliateDashboardRouteImport } from './routes/affiliate-dashboard'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliateProductsPartnerRouteImport } from './routes/affiliate-products.$partner'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyCapAppRoute = TruyCapAppRouteImport.update({
  id: '/truy-cap-app',
  path: '/truy-cap-app',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamRoute = SanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KienThucRoute = KienThucRouteImport.update({
  id: '/kien-thuc',
  path: '/kien-thuc',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoiNghiepRoute = KhoiNghiepRouteImport.update({
  id: '/khoi-nghiep',
  path: '/khoi-nghiep',
  getParentRoute: () => rootRouteImport,
} as any)
const KenhAffiliateRoute = KenhAffiliateRouteImport.update({
  id: '/kenh-affiliate',
  path: '/kenh-affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const HocVienRoute = HocVienRouteImport.update({
  id: '/hoc-vien',
  path: '/hoc-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const HocAiRoute = HocAiRouteImport.update({
  id: '/hoc-ai',
  path: '/hoc-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CongCuAiRoute = CongCuAiRouteImport.update({
  id: '/cong-cu-ai',
  path: '/cong-cu-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDashboardRoute = AffiliateDashboardRouteImport.update({
  id: '/affiliate-dashboard',
  path: '/affiliate-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateProductsPartnerRoute =
  AffiliateProductsPartnerRouteImport.update({
    id: '/affiliate-products/$partner',
    path: '/affiliate-products/$partner',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliate': typeof AffiliateRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/auth': typeof AuthRoute
  '/cong-cu-ai': typeof CongCuAiRoute
  '/dashboard': typeof DashboardRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/hoc-ai': typeof HocAiRoute
  '/hoc-vien': typeof HocVienRoute
  '/kenh-affiliate': typeof KenhAffiliateRoute
  '/khoi-nghiep': typeof KhoiNghiepRoute
  '/kien-thuc': typeof KienThucRoute
  '/reset-password': typeof ResetPasswordRoute
  '/san-pham': typeof SanPhamRoute
  '/truy-cap-app': typeof TruyCapAppRoute
  '/workshop': typeof WorkshopRoute
  '/affiliate-products/$partner': typeof AffiliateProductsPartnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliate': typeof AffiliateRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/auth': typeof AuthRoute
  '/cong-cu-ai': typeof CongCuAiRoute
  '/dashboard': typeof DashboardRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/hoc-ai': typeof HocAiRoute
  '/hoc-vien': typeof HocVienRoute
  '/kenh-affiliate': typeof KenhAffiliateRoute
  '/khoi-nghiep': typeof KhoiNghiepRoute
  '/kien-thuc': typeof KienThucRoute
  '/reset-password': typeof ResetPasswordRoute
  '/san-pham': typeof SanPhamRoute
  '/truy-cap-app': typeof TruyCapAppRoute
  '/workshop': typeof WorkshopRoute
  '/affiliate-products/$partner': typeof AffiliateProductsPartnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliate': typeof AffiliateRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/auth': typeof AuthRoute
  '/cong-cu-ai': typeof CongCuAiRoute
  '/dashboard': typeof DashboardRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/hoc-ai': typeof HocAiRoute
  '/hoc-vien': typeof HocVienRoute
  '/kenh-affiliate': typeof KenhAffiliateRoute
  '/khoi-nghiep': typeof KhoiNghiepRoute
  '/kien-thuc': typeof KienThucRoute
  '/reset-password': typeof ResetPasswordRoute
  '/san-pham': typeof SanPhamRoute
  '/truy-cap-app': typeof TruyCapAppRoute
  '/workshop': typeof WorkshopRoute
  '/affiliate-products/$partner': typeof AffiliateProductsPartnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliate'
    | '/affiliate-dashboard'
    | '/auth'
    | '/cong-cu-ai'
    | '/dashboard'
    | '/gioi-thieu'
    | '/hoc-ai'
    | '/hoc-vien'
    | '/kenh-affiliate'
    | '/khoi-nghiep'
    | '/kien-thuc'
    | '/reset-password'
    | '/san-pham'
    | '/truy-cap-app'
    | '/workshop'
    | '/affiliate-products/$partner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/affiliate'
    | '/affiliate-dashboard'
    | '/auth'
    | '/cong-cu-ai'
    | '/dashboard'
    | '/gioi-thieu'
    | '/hoc-ai'
    | '/hoc-vien'
    | '/kenh-affiliate'
    | '/khoi-nghiep'
    | '/kien-thuc'
    | '/reset-password'
    | '/san-pham'
    | '/truy-cap-app'
    | '/workshop'
    | '/affiliate-products/$partner'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliate'
    | '/affiliate-dashboard'
    | '/auth'
    | '/cong-cu-ai'
    | '/dashboard'
    | '/gioi-thieu'
    | '/hoc-ai'
    | '/hoc-vien'
    | '/kenh-affiliate'
    | '/khoi-nghiep'
    | '/kien-thuc'
    | '/reset-password'
    | '/san-pham'
    | '/truy-cap-app'
    | '/workshop'
    | '/affiliate-products/$partner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AffiliateRoute: typeof AffiliateRoute
  AffiliateDashboardRoute: typeof AffiliateDashboardRoute
  AuthRoute: typeof AuthRoute
  CongCuAiRoute: typeof CongCuAiRoute
  DashboardRoute: typeof DashboardRoute
  GioiThieuRoute: typeof GioiThieuRoute
  HocAiRoute: typeof HocAiRoute
  HocVienRoute: typeof HocVienRoute
  KenhAffiliateRoute: typeof KenhAffiliateRoute
  KhoiNghiepRoute: typeof KhoiNghiepRoute
  KienThucRoute: typeof KienThucRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SanPhamRoute: typeof SanPhamRoute
  TruyCapAppRoute: typeof TruyCapAppRoute
  WorkshopRoute: typeof WorkshopRoute
  AffiliateProductsPartnerRoute: typeof AffiliateProductsPartnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truy-cap-app': {
      id: '/truy-cap-app'
      path: '/truy-cap-app'
      fullPath: '/truy-cap-app'
      preLoaderRoute: typeof TruyCapAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham': {
      id: '/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof SanPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kien-thuc': {
      id: '/kien-thuc'
      path: '/kien-thuc'
      fullPath: '/kien-thuc'
      preLoaderRoute: typeof KienThucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoi-nghiep': {
      id: '/khoi-nghiep'
      path: '/khoi-nghiep'
      fullPath: '/khoi-nghiep'
      preLoaderRoute: typeof KhoiNghiepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kenh-affiliate': {
      id: '/kenh-affiliate'
      path: '/kenh-affiliate'
      fullPath: '/kenh-affiliate'
      preLoaderRoute: typeof KenhAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-vien': {
      id: '/hoc-vien'
      path: '/hoc-vien'
      fullPath: '/hoc-vien'
      preLoaderRoute: typeof HocVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-ai': {
      id: '/hoc-ai'
      path: '/hoc-ai'
      fullPath: '/hoc-ai'
      preLoaderRoute: typeof HocAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-cu-ai': {
      id: '/cong-cu-ai'
      path: '/cong-cu-ai'
      fullPath: '/cong-cu-ai'
      preLoaderRoute: typeof CongCuAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-dashboard': {
      id: '/affiliate-dashboard'
      path: '/affiliate-dashboard'
      fullPath: '/affiliate-dashboard'
      preLoaderRoute: typeof AffiliateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-products/$partner': {
      id: '/affiliate-products/$partner'
      path: '/affiliate-products/$partner'
      fullPath: '/affiliate-products/$partner'
      preLoaderRoute: typeof AffiliateProductsPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AffiliateRoute: AffiliateRoute,
  AffiliateDashboardRoute: AffiliateDashboardRoute,
  AuthRoute: AuthRoute,
  CongCuAiRoute: CongCuAiRoute,
  DashboardRoute: DashboardRoute,
  GioiThieuRoute: GioiThieuRoute,
  HocAiRoute: HocAiRoute,
  HocVienRoute: HocVienRoute,
  KenhAffiliateRoute: KenhAffiliateRoute,
  KhoiNghiepRoute: KhoiNghiepRoute,
  KienThucRoute: KienThucRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SanPhamRoute: SanPhamRoute,
  TruyCapAppRoute: TruyCapAppRoute,
  WorkshopRoute: WorkshopRoute,
  AffiliateProductsPartnerRoute: AffiliateProductsPartnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
